// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvhdbtuoipnelhoeyymp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2aGRidHVvaXBuZWxob2V5eW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTkwMjUsImV4cCI6MjA2MjQ3NTAyNX0.bQsqsyoTChzXHUGFPzbSEObQ2ygnZ2Pqzfjt_K9RY2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);